"""Public interface for Jace's local voice subsystem."""

from jace.voice.service import (
    DEFAULT_KOKORO_LANGUAGE,
    DEFAULT_KOKORO_MODEL,
    DEFAULT_KOKORO_SPEED,
    DEFAULT_KOKORO_VOICE,
    DEFAULT_KOKORO_VOICES,
    KOKORO_ROOT,
    MAX_AUDIO_BYTES,
    MIN_AUDIO_BYTES,
    WELCOME_LINE,
    TranscriptionResult,
    VoiceDecodeError,
    VoiceError,
    VoiceRuntimeError,
    VoiceService,
    VoiceUnavailableError,
    get_voice_status,
    synthesize_speech,
    synthesise_speech,
    transcribe_audio,
    transcribe_upload,
    voice_service,
    voice_status,
)

__all__ = [
    "DEFAULT_KOKORO_LANGUAGE",
    "DEFAULT_KOKORO_MODEL",
    "DEFAULT_KOKORO_SPEED",
    "DEFAULT_KOKORO_VOICE",
    "DEFAULT_KOKORO_VOICES",
    "KOKORO_ROOT",
    "MAX_AUDIO_BYTES",
    "MIN_AUDIO_BYTES",
    "WELCOME_LINE",
    "TranscriptionResult",
    "VoiceDecodeError",
    "VoiceError",
    "VoiceRuntimeError",
    "VoiceService",
    "VoiceUnavailableError",
    "get_voice_status",
    "synthesize_speech",
    "synthesise_speech",
    "transcribe_audio",
    "transcribe_upload",
    "voice_service",
    "voice_status",
]
